In [1]:
#First, imports
import time 
import requests
import json
import csv
import pprint
import pandas as pd
from Config import apikey

In [2]:
#Start by accessing api
base_url=f"https://api.polygon.io/v2/aggs/ticker/"
#Beer=BUDweiser and coors(TAP), Soda=COKE and PEPsi, Coffee=dutchBROS and StarBUX 
tickers=["BUD","TAP","COKE","PEP","BROS","SBUX"]
data_list=[]

In [3]:
def iterate_months():
    start_month = 11
    for year in range(2021, 2024):
        for month in range(start_month, 12):
            yield f"{year}-{month:02d}-01"
        start_month = 1

In [4]:
#Responses in following string
# C- Close price                # O- Open price  
# H- High price                 # T- Unix time
# L- Low price                  # V- Volume
# N- Number of transactions     # VW- Volume weighted

In [5]:
#Gather data and append to a list
for tick in tickers:
    
    #Makes the print a little prettier
    print("-------------------------")
    print(f"Now Finding: {tick}")
    print("-------------------------")
    
    #Iterate, find and append data
    for month in iterate_months():
        
        #Shows the date time
        print("-------------------------")
        print(f"Result Date: {month}")
        print("-------------------------")
        
        full_url=base_url+f"{tick}/range/12/month/{month}/{month}?adjusted=true&sort=asc&limit=120&apiKey={apikey}"
        data = requests.get(full_url)
        data_json = data.json()
        formatted_data = pprint.pformat(data_json)
        print(formatted_data)
        data_list.append(data_json)
        
        #limited to 5 pulls per miniute, timer allows for the sixth call
        time.sleep(13)
        
        #Stop on todays date
        if month == "2023-10-01":
            break 
    
#Quality of life to say when its done
print("-------------------------")
print(f"Done!")
print("-------------------------")

-------------------------
Now Finding: BUD
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'b5296d2db4a3778378bc3a94ba2df909',
 'results': [{'c': 59.31,
              'h': 67.91,
              'l': 52.65,
              'n': 1957405,
              'o': 60.21,
              't': 1635739200000,
              'v': 195949135.0,
              'vw': 59.8907}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '8c6bd9f935f6a89995d0f4551039be15',
 'results': [{'c': 53.94,
              'h': 67.91,
              'l': 50.59,
              'n': 2105726,
              'o': 62.43,
              't': 1641013200000,
              'v': 185073263.0,
              'vw': 58.7384}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5a5d15c0045763f5d765121a09700063',
 'results': [{'c': 55.02,
              'h': 66.05,
              'l': 50.59,
              'n': 2060645,
              'o': 64.01,
              't': 1643691600000,
              'v': 176759102.0,
              'vw': 57.2436}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '44676d9f0cfef0282f5f2c6f2bcb85f8',
 'results': [{'c': 52.51,
              'h': 63.45,
              'l': 50.59,
              'n': 2053783,
              'o': 59.94,
              't': 1646110800000,
              'v': 177299717.0,
              'vw': 55.898}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '00d49fdea0a81c54f219ab93a0bbee23',
 'results': [{'c': 48.57,
              'h': 63.45,
              'l': 47.23,
              'n': 1951050,
              'o': 60.79,
              't': 1648785600000,
              'v': 160603099.0,
              'vw': 54.0878}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '77a840ba3e49b04a18a2770f8e1d9610',
 'results': [{'c': 45.23,
              'h': 58.37,
              'l': 44.51,
              'n': 2004952,
              'o': 56.98,
              't': 1651377600000,
              'v': 170988591.0,
              'vw': 51.7573}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '8b311a1e05b31d6a63a6436c75ca2757',
 'results': [{'c': 55.53,
              'h': 56.59,
              'l': 44.51,
              'n': 2015899,
              'o': 56.4,
              't': 1654056000000,
              'v': 172949903.0,
              'vw': 50.9943}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'd43066fd3834b171e1e4200c96567785',
 'results': [{'c': 59.37,
              'h': 61.63,
              'l': 44.51,
              'n': 1912934,
              'o': 53.92,
              't': 1656648000000,
              'v': 165669941.0,
              'vw': 51.654}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'cee12b51c26ca0498e9a59634bf27e52',
 'results': [{'c': 59.8,
              'h': 61.89,
              'l': 44.51,
              'n': 1925862,
              'o': 53,
              't': 1659326400000,
              'v': 166972811.0,
              'vw': 52.6036}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'b195e5256b643ccceafd49b2707f5196',
 'results': [{'c': 60.79,
              'h': 61.89,
              'l': 44.51,
              'n': 1955362,
              'o': 47.47,
              't': 1662004800000,
              'v': 165184132.0,
              'vw': 53.8958}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '091fc132cc0340557b96cb5154ddb7b0',
 'results': [{'c': 62.18,
              'h': 62.53,
              'l': 44.51,
              'n': 2075917,
              'o': 44.99,
              't': 1664596800000,
              'v': 169385926.0,
              'vw': 56.4788}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '52319d8ae9557cf3738a8a6d7b77f64f',
 'results': [{'c': 65.65,
              'h': 67.09,
              'l': 48.685,
              'n': 2286932,
              'o': 51.44,
              't': 1667275200000,
              'v': 190980699.0,
              'vw': 60.6309}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '0d417fc43bf0250bb3bbcc0ebe2e0ea4',
 'results': [{'c': 56.36,
              'h': 67.09,
              'l': 52.93,
              'n': 3015781,
              'o': 60.31,
              't': 1672549200000,
              'v': 255697533.0,
              'vw': 60.4331}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'dd9f1ebd33899db0c225a936ae028162',
 'results': [{'c': 58.56,
              'h': 67.09,
              'l': 52.93,
              'n': 3082445,
              'o': 60.66,
              't': 1675227600000,
              'v': 263647158.0,
              'vw': 60.0174}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '002bb7846c9ca9a85f4b6b404ab55829',
 'results': [{'c': 56.2,
              'h': 67.09,
              'l': 52.93,
              'n': 3223618,
              'o': 61.2,
              't': 1677646800000,
              'v': 282078590.0,
              'vw': 59.5769}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '13d2e0300e88c2dea4859d88cb6d40a6',
 'results': [{'c': 56.44,
              'h': 67.01,
              'l': 52.93,
              'n': 3239070,
              'o': 66.52,
              't': 1680321600000,
              'v': 282846458.0,
              'vw': 58.8888}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1f07e1db8f50069bb32f782cd122f8b5',
 'results': [{'c': 53.28,
              'h': 66.32,
              'l': 51.66,
              'n': 3257020,
              'o': 65.11,
              't': 1682913600000,
              'v': 275081831.0,
              'vw': 56.8354}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 106,
 'request_id': '0ede63af3dee6d8da82d82071d830942',
 'results': [{'c': 56.835,
              'h': 59.21,
              'l': 51.66,
              'n': 2754035,
              'o': 53.71,
              't': 1685592000000,
              'v': 234596875.0,
              'vw': 55.8386}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}

-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 85,
 'request_id': 'd212f02f5e0bc27fd3ca6dcf648ba164',
 'results': [{'c': 56.835,
              'h': 59.21,
              'l': 51.66,
              'n': 2101356,
              'o': 57,
              't': 1688184000000,
              'v': 175473641.0,
              'vw': 55.8136}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 65,
 'request_id': 'eff7f9d8cdb8152f44242fc57656fa23',
 'results': [{'c': 56.835,
              'h': 58.28,
              'l': 51.66,
              'n': 1681592,
              'o': 57.15,
              't': 1690862400000,
              'v': 135735040.0,
              'vw': 55.264}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 42,
 'request_id': '029201fd335839fb3885add9ea1dbe07',
 'results': [{'c': 56.835,
              'h': 57.79,
              'l': 51.66,
              'n': 1135227,
              'o': 56.91,
              't': 1693540800000,
              'v': 89242280.0,
              'vw': 54.595}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 22,
 'request_id': '3d65311a44e42ef8db178a1a32b16fde',
 'results': [{'c': 56.835,
              'h': 56.965,
              'l': 51.66,
              'n': 656705,
              'o': 54.51,
              't': 1696132800000,
              'v': 52038650.0,
              'vw': 53.5089}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Now Finding: TAP
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4a9b7f2189cd588c737d49b32c6824a8',
 'results': [{'c': 53.77,
              'h': 57.45,
              'l': 42.6,
              'n': 2230835,
              'o': 44.11,
              't': 1635739200000,
              'v': 193433235.0,
              'vw': 49.1388}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '3d7b2bcae75d8a211593613d982bbebb',
 'results': [{'c': 55.77,
              'h': 57.45,
              'l': 46.47,
              'n': 2422641,
              'o': 46.54,
              't': 1641013200000,
              'v': 194100944.0,
              'vw': 51.7757}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '15af4fc1f0bd2f810c3d253dfea35d7f',
 'results': [{'c': 58.22,
              'h': 59.38,
              'l': 47.34,
              'n': 2409340,
              'o': 47.58,
              't': 1643691600000,
              'v': 189620132.0,
              'vw': 53.0272}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'f75ff56c7afac9225310453126d7bf22',
 'results': [{'c': 56.09,
              'h': 60.12,
              'l': 49.12,
              'n': 2434905,
              'o': 51.76,
              't': 1646110800000,
              'v': 188182783.0,
              'vw': 54.1061}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '3743389c3a2f1ccad8d9933bbc6734df',
 'results': [{'c': 49.15,
              'h': 60.12,
              'l': 49.1,
              'n': 2372252,
              'o': 53.39,
              't': 1648785600000,
              'v': 177858495.0,
              'vw': 54.2744}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'a05df6082d4134b42fa7531bd3600cfd',
 'results': [{'c': 48.24,
              'h': 60.12,
              'l': 46.685,
              'n': 2345719,
              'o': 54.52,
              't': 1651377600000,
              'v': 173785804.0,
              'vw': 53.5571}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '05836c1c4bfa2f51fee428458589dd8f',
 'results': [{'c': 53.5,
              'h': 60.12,
              'l': 46.685,
              'n': 2286420,
              'o': 55.98,
              't': 1654056000000,
              'v': 164117982.0,
              'vw': 52.9584}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'c0e5f4af3b1a21d0beb428151091db89',
 'results': [{'c': 50.77,
              'h': 60.12,
              'l': 46.685,
              'n': 2250213,
              'o': 54.48,
              't': 1656648000000,
              'v': 159448782.0,
              'vw': 53.0197}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '88ea037c1cebbcaea347f7e10d497c5c',
 'results': [{'c': 49.98,
              'h': 60.12,
              'l': 46.685,
              'n': 2218999,
              'o': 59.49,
              't': 1659326400000,
              'v': 153933353.0,
              'vw': 51.7091}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'a6698ae92f2e03559df5cec6ee4cd23e',
 'results': [{'c': 53.5,
              'h': 56.28,
              'l': 46.685,
              'n': 2293933,
              'o': 50.96,
              't': 1662004800000,
              'v': 158599886.0,
              'vw': 51.2054}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '47ebc2abadfddc34f0dcf4a3d5985bfa',
 'results': [{'c': 50.7,
              'h': 56.28,
              'l': 46.685,
              'n': 2453742,
              'o': 48.29,
              't': 1664596800000,
              'v': 170836918.0,
              'vw': 51.626}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1bb97bf16cd21e71a490cf30a7629a71',
 'results': [{'c': 58.71,
              'h': 59.26,
              'l': 46.9,
              'n': 2632656,
              'o': 50.35,
              't': 1667275200000,
              'v': 185506016.0,
              'vw': 52.6181}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '81f924d5132511862efeb6645bff2917',
 'results': [{'c': 65.67,
              'h': 68.13,
              'l': 48.485,
              'n': 3218355,
              'o': 50.55,
              't': 1672549200000,
              'v': 240311486.0,
              'vw': 57.69}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '641b3d8a5959d8942901ccb643728899',
 'results': [{'c': 70.67,
              'h': 70.7382,
              'l': 49.32,
              'n': 3287014,
              'o': 52.4,
              't': 1675227600000,
              'v': 247607380.0,
              'vw': 60.0345}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}

-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '9b012537eafae88aaa2561689c80fc47',
 'results': [{'c': 62.78,
              'h': 70.9,
              'l': 49.32,
              'n': 3405737,
              'o': 52.88,
              't': 1677646800000,
              'v': 255480911.0,
              'vw': 61.9304}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'f19621ddac63f6b1c4e004b4269abc9a',
 'results': [{'c': 63.4,
              'h': 70.9,
              'l': 51.45,
              'n': 3326555,
              'o': 51.81,
              't': 1680321600000,
              'v': 247201745.0,
              'vw': 63.7097}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4d355be7551449a95dbfeef5360db964',
 'results': [{'c': 58.34,
              'h': 70.9,
              'l': 57.34,
              'n': 3296120,
              'o': 59.47,
              't': 1682913600000,
              'v': 242219431.0,
              'vw': 64.4123}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 106,
 'request_id': '726cf407b2c1f62a90dabca5ec15f0bf',
 'results': [{'c': 57.91,
              'h': 70.9,
              'l': 56.5,
              'n': 2720949,
              'o': 61.51,
              't': 1685592000000,
              'v': 192940939.0,
              'vw': 64.4136}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 85,
 'request_id': '97bb7403ffaf5305fd152f2e4fd678b1',
 'results': [{'c': 57.88,
              'h': 70.9,
              'l': 56.5,
              'n': 2108162,
              'o': 65.64,
              't': 1688184000000,
              'v': 145347739.0,
              'vw': 63.9558}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 65,
 'request_id': '28d838786980987f6dfa370667dd0c09',
 'results': [{'c': 57.88,
              'h': 68.64,
              'l': 56.5,
              'n': 1587123,
              'o': 65.15,
              't': 1690862400000,
              'v': 103496822.0,
              'vw': 62.4}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 42,
 'request_id': 'acc40935eac59d71a181324c9d3bdab7',
 'results': [{'c': 57.88,
              'h': 65.31,
              'l': 56.5,
              'n': 984489,
              'o': 63.57,
              't': 1693540800000,
              'v': 63151989.0,
              'vw': 61.0607}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 22,
 'request_id': '243d715c83cd73f4440986717cd4294a',
 'results': [{'c': 57.88,
              'h': 63.84,
              'l': 56.5,
              'n': 566567,
              'o': 63.52,
              't': 1696132800000,
              'v': 35741875.0,
              'vw': 59.2229}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Now Finding: COKE
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '0a1f3f333f186228042deb0bed893547',
 'results': [{'c': 474.8,
              'h': 638,
              'l': 400.5855,
              'n': 338860,
              'o': 404.99,
              't': 1635739200000,
              'v': 4290350.0,
              'vw': 528.666}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '99236449ddce59973cc82ac72e6725de',
 'results': [{'c': 551.82,
              'h': 656.11,
              'l': 420.34,
              'n': 422823,
              'o': 616.35,
              't': 1641013200000,
              'v': 4898201.0,
              'vw': 527.0292}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4a1a5d546eb6d84b6ee46c4ca3433a89',
 'results': [{'c': 494.11,
              'h': 656.11,
              'l': 420.34,
              'n': 460406,
              'o': 576.65,
              't': 1643691600000,
              'v': 6426679.0,
              'vw': 516.5643}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'dd3cb7bda7256bd5e8fc0689a1c5d100',
 'results': [{'c': 527.18,
              'h': 656.11,
              'l': 426.402,
              'n': 458678,
              'o': 491.77,
              't': 1646110800000,
              'v': 6463730.0,
              'vw': 514.2551}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4b87abc1adb2ef4f153eb7809d50036a',
 'results': [{'c': 421.83,
              'h': 656.11,
              'l': 420.2097,
              'n': 444723,
              'o': 502,
              't': 1648785600000,
              'v': 6345015.0,
              'vw': 511.8945}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '8342cb5db0b0f766bbd6a8a120768721',
 'results': [{'c': 430.78,
              'h': 656.11,
              'l': 405.03,
              'n': 444453,
              'o': 443.77,
              't': 1651377600000,
              'v': 6381374.0,
              'vw': 505.4479}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '0910eff0811b85706a397ac24b465959',
 'results': [{'c': 466.44,
              'h': 656.11,
              'l': 405.03,
              'n': 421827,
              'o': 562.8,
              't': 1654056000000,
              'v': 6499636.0,
              'vw': 499.1969}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'e6f3d61739261b52096b838ddf0fcb98',
 'results': [{'c': 511.7,
              'h': 597.485,
              'l': 405.03,
              'n': 380407,
              'o': 558.24,
              't': 1656648000000,
              'v': 6414870.0,
              'vw': 487.5256}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'e5db9d56e52beed5874fc17d8ffce163',
 'results': [{'c': 483.42,
              'h': 555.8239,
              'l': 405.03,
              'n': 337607,
              'o': 514.12,
              't': 1659326400000,
              'v': 4850957.0,
              'vw': 477.6951}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'ace6061de927926345a98bb3ecbc9a84',
 'results': [{'c': 570.9,
              'h': 576,
              'l': 405.03,
              'n': 334324,
              'o': 476.89,
              't': 1662004800000,
              'v': 4872410.0,
              'vw': 479.3821}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}

-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '09be736acdf26ff98911c2bbeb7a4407',
 'results': [{'c': 525.28,
              'h': 579.85,
              'l': 412.71,
              'n': 342082,
              'o': 416.1,
              't': 1664596800000,
              'v': 4904729.0,
              'vw': 495.7912}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'a68b7821a0e4bb8f54295cfa086ff935',
 'results': [{'c': 560.45,
              'h': 579.85,
              'l': 450.85,
              'n': 328820,
              'o': 491.28,
              't': 1667275200000,
              'v': 4736854.0,
              'vw': 508.36}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'c1d316d0c4416ce682f924a6a3837614',
 'results': [{'c': 639.57,
              'h': 694.2,
              'l': 470,
              'n': 366467,
              'o': 515.41,
              't': 1672549200000,
              'v': 4611313.0,
              'vw': 569.5161}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '30abaa9ac57c643f4930bab6d160d07c',
 'results': [{'c': 638.5,
              'h': 694.2,
              'l': 492.76,
              'n': 371198,
              'o': 507.12,
              't': 1675227600000,
              'v': 4601969.0,
              'vw': 591.9576}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1301bd02cfb7db8fdf13a2b6927c5a6b',
 'results': [{'c': 689.58,
              'h': 745.53,
              'l': 495.11,
              'n': 379581,
              'o': 557.36,
              't': 1677646800000,
              'v': 4661869.0,
              'vw': 618.9908}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '22c94ed0f1e8925afb887919a3655464',
 'results': [{'c': 655.26,
              'h': 745.53,
              'l': 519.14,
              'n': 387334,
              'o': 534.99,
              't': 1680321600000,
              'v': 4687709.0,
              'vw': 647.4158}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'a72a7f84a432cb091d7cebfa724c910e',
 'results': [{'c': 625.67,
              'h': 745.53,
              'l': 584.69,
              'n': 395837,
              'o': 589.32,
              't': 1682913600000,
              'v': 4723555.0,
              'vw': 658.0016}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 106,
 'request_id': 'c65397709c1834b1afdbf806b678c120',
 'results': [{'c': 636.29,
              'h': 745.53,
              'l': 614.22,
              'n': 336479,
              'o': 660.41,
              't': 1685592000000,
              'v': 4029537.0,
              'vw': 660.1345}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 85,
 'request_id': '01a75ffa35026cc6474c70a64521a521',
 'results': [{'c': 636.29,
              'h': 745.53,
              'l': 614.22,
              'n': 258728,
              'o': 634.49,
              't': 1688184000000,
              'v': 3104191.0,
              'vw': 660.2122}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 65,
 'request_id': '531e65b0b573d980df74bc56448f02cd',
 'results': [{'c': 636.29,
              'h': 745.53,
              'l': 614.22,
              'n': 198998,
              'o': 634.25,
              't': 1690862400000,
              'v': 2333694.0,
              'vw': 668.2312}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 42,
 'request_id': '2b0a92d90f9f32de09fb77a32fd46667',
 'results': [{'c': 636.29,
              'h': 701,
              'l': 614.22,
              'n': 128260,
              'o': 701,
              't': 1693540800000,
              'v': 1348883.0,
              'vw': 648.5056}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 22,
 'request_id': 'db6ae5a03850fc0ca6c80c5f0fec2469',
 'results': [{'c': 636.29,
              'h': 670,
              'l': 614.22,
              'n': 59378,
              'o': 637.72,
              't': 1696132800000,
              'v': 646057,
              'vw': 636.7942}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'COKE'}
-------------------------
Now Finding: PEP
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '75cb461dead7e13b9d53a7e098eb5a2d',
 'results': [{'c': 172.15,
              'h': 177.24,
              'l': 153.37,
              'n': 7799720,
              'o': 161.2,
              't': 1635739200000,
              'v': 604042310.0,
              'vw': 167.6689}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'a9acf2891c9b3b059b4da4a378782b98',
 'results': [{'c': 166.13,
              'h': 177.62,
              'l': 153.37,
              'n': 8689823,
              'o': 172.2,
              't': 1641013200000,
              'v': 677766860.0,
              'vw': 167.9066}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '2afa47a81bbe95bb8388d36f19d46dcf',
 'results': [{'c': 169.85,
              'h': 177.62,
              'l': 153.37,
              'n': 8441179,
              'o': 173.15,
              't': 1643691600000,
              'v': 645532362.0,
              'vw': 167.0945}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '0a78c8a9eaa61086f58805cb653bb545',
 'results': [{'c': 180.17,
              'h': 181.07,
              'l': 153.37,
              'n': 7970061,
              'o': 163.07,
              't': 1646110800000,
              'v': 598254882.0,
              'vw': 167.8107}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '46a887ef70a1faf1a370cd49b7a9543a',
 'results': [{'c': 168.6,
              'h': 181.07,
              'l': 154.8576,
              'n': 7781960,
              'o': 167.89,
              't': 1648785600000,
              'v': 584754701.0,
              'vw': 169.8246}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '7aa55d054a43e408a651335600e2ff8d',
 'results': [{'c': 171.46,
              'h': 181.07,
              'l': 154.8576,
              'n': 7965519,
              'o': 172.995,
              't': 1651377600000,
              'v': 600179237.0,
              'vw': 169.0204}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}

-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4b1475bde04a601b2fe825bc57010b29',
 'results': [{'c': 181.33,
              'h': 183.58,
              'l': 154.8576,
              'n': 7738471,
              'o': 168.18,
              't': 1654056000000,
              'v': 569558724.0,
              'vw': 170.8474}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'b23c328c1fabb0d2ff2b34a0cb98b66e',
 'results': [{'c': 181.23,
              'h': 186.84,
              'l': 160.98,
              'n': 7574118,
              'o': 166.74,
              't': 1656648000000,
              'v': 566890459.0,
              'vw': 174.7018}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '0528b42018c89894a1fe2b3805b53d2f',
 'results': [{'c': 169.88,
              'h': 186.84,
              'l': 160.98,
              'n': 7600312,
              'o': 174.55,
              't': 1659326400000,
              'v': 565165245.0,
              'vw': 175.7339}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '27a8114f5d53197075d4b7d0cb3af681',
 'results': [{'c': 176.31,
              'h': 186.84,
              'l': 160.98,
              'n': 8083268,
              'o': 170.9201,
              't': 1662004800000,
              'v': 601469619.0,
              'vw': 175.0036}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'c551909844ab61ff8c467cdf638ab2b8',
 'results': [{'c': 179.09,
              'h': 186.84,
              'l': 160.98,
              'n': 8051825,
              'o': 163.52,
              't': 1664596800000,
              'v': 586966686.0,
              'vw': 176.1001}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '9e1c74cd59c8e5efdd52e8489e63363b',
 'results': [{'c': 189.71,
              'h': 190.18,
              'l': 167.05,
              'n': 7671600,
              'o': 180.94,
              't': 1667275200000,
              'v': 546772075.0,
              'vw': 178.0092}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '2abf037e679ab98aca62ed8f730a5426',
 'results': [{'c': 184.89,
              'h': 196.88,
              'l': 167.05,
              'n': 7724140,
              'o': 180.59,
              't': 1672549200000,
              'v': 544020091.0,
              'vw': 179.9529}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'b3993c449bb66946487f2a1b36c62530',
 'results': [{'c': 191.36,
              'h': 196.88,
              'l': 167.05,
              'n': 8037588,
              'o': 170.88,
              't': 1675227600000,
              'v': 567840657.0,
              'vw': 182.2497}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'f6a566dfb37d53daf6628651449b38c8',
 'results': [{'c': 177.05,
              'h': 196.88,
              'l': 169.12,
              'n': 7991935,
              'o': 172.32,
              't': 1677646800000,
              'v': 548298615.0,
              'vw': 184.1244}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '2a0db725d6f36666ff554047174da528',
 'results': [{'c': 175.27,
              'h': 196.88,
              'l': 173.48,
              'n': 8105101,
              'o': 181.9,
              't': 1680321600000,
              'v': 546540307.0,
              'vw': 184.5972}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '61af98ccaeb40ab5bb9693612b213f3e',
 'results': [{'c': 160.56,
              'h': 196.88,
              'l': 155.83,
              'n': 8940813,
              'o': 190.45,
              't': 1682913600000,
              'v': 604201203.0,
              'vw': 180.0693}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 106,
 'request_id': '674b627e0fc4cf200c4fe5913c3f93fb',
 'results': [{'c': 163.06,
              'h': 192.38,
              'l': 155.83,
              'n': 8348571,
              'o': 182.42,
              't': 1685592000000,
              'v': 540939353.0,
              'vw': 177.0571}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 85,
 'request_id': '588f75543a9ada8a06678b656f9522ea',
 'results': [{'c': 163.08,
              'h': 192.38,
              'l': 155.83,
              'n': 6948484,
              'o': 184.3,
              't': 1688184000000,
              'v': 439999698.0,
              'vw': 175.4352}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 65,
 'request_id': '582e574910a57b90a0a65e7144055ef3',
 'results': [{'c': 163.08,
              'h': 189.97,
              'l': 155.83,
              'n': 5303249,
              'o': 187.49,
              't': 1690862400000,
              'v': 329617929.0,
              'vw': 171.4455}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 42,
 'request_id': '1166eef03e0295215a4c67acb8dbb357',
 'results': [{'c': 163.08,
              'h': 181.82,
              'l': 155.83,
              'n': 3767655,
              'o': 178.73,
              't': 1693540800000,
              'v': 237236096.0,
              'vw': 167.4673}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 22,
 'request_id': '1edb11771c32730b803a88ffc41114b3',
 'results': [{'c': 163.08,
              'h': 170,
              'l': 155.83,
              'n': 2316648,
              'o': 169.08,
              't': 1696132800000,
              'v': 141409042.0,
              'vw': 161.7754}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Now Finding: BROS
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '33b84af60098e3919d6611bfab3e0e63',
 'results': [{'c': 51.19,
              'h': 81.4,
              'l': 38.11,
              'n': 2639245,
              'o': 77.5,
              't': 1635739200000,
              'v': 236976558.0,
              'vw': 53.4792}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '430364e2022b8f877e4f22a517e3d3c8',
 'results': [{'c': 36.87,
              'h': 66,
              'l': 20.05,
              'n': 2699940,
              'o': 51.47,
              't': 1641013200000,
              'v': 256441484.0,
              'vw': 44.2476}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}

-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1422a3b83db7605bb343502ef18b2184',
 'results': [{'c': 36.24,
              'h': 66,
              'l': 20.05,
              'n': 2413430,
              'o': 52.02,
              't': 1643691600000,
              'v': 227739644.0,
              'vw': 43.3747}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '3c53d92aad7106b2c91b1ecbd1e2847f',
 'results': [{'c': 40.28,
              'h': 66,
              'l': 20.05,
              'n': 2340202,
              'o': 49.11,
              't': 1646110800000,
              'v': 220396837.0,
              'vw': 41.6542}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '072458b13e6340cb56b948e6d094e189',
 'results': [{'c': 34.19,
              'h': 58.6942,
              'l': 20.05,
              'n': 2058481,
              'o': 56.43,
              't': 1648785600000,
              'v': 186041506.0,
              'vw': 37.4877}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '7fe7e2572cd01d64d3d0bbf8a6df8ec1',
 'results': [{'c': 34.21,
              'h': 54.18,
              'l': 20.05,
              'n': 2014828,
              'o': 47.8,
              't': 1651377600000,
              'v': 180719365.0,
              'vw': 34.5737}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5e9ea1b9ea98e06dfe104a5b923b958b',
 'results': [{'c': 34.11,
              'h': 54.18,
              'l': 27.94,
              'n': 1726725,
              'o': 37.47,
              't': 1654056000000,
              'v': 139577748.0,
              'vw': 36.8808}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '97f3bcc15c2140ae8912a79425ef02b2',
 'results': [{'c': 30.07,
              'h': 54.18,
              'l': 27.94,
              'n': 1794813,
              'o': 31.67,
              't': 1656648000000,
              'v': 137070749.0,
              'vw': 36.4363}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '7cae4680198ea190f65455496c57a92b',
 'results': [{'c': 34,
              'h': 54.18,
              'l': 26.93,
              'n': 1954081,
              'o': 37.25,
              't': 1659326400000,
              'v': 147629695.0,
              'vw': 35.6386}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5ace3b113335cab79133a319fbaeebb6',
 'results': [{'c': 34.03,
              'h': 41.4399,
              'l': 26.93,
              'n': 1958424,
              'o': 35.9,
              't': 1662004800000,
              'v': 143300441.0,
              'vw': 33.961}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'f0a59ab9dda4a64747a3381ae87e44b4',
 'results': [{'c': 28.66,
              'h': 41.4399,
              'l': 26.93,
              'n': 1973148,
              'o': 31.5,
              't': 1664596800000,
              'v': 145046280.0,
              'vw': 33.5112}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '40953e806b3f9d974c58ee75da4cdc96',
 'results': [{'c': 30.28,
              'h': 41.4399,
              'l': 26.93,
              'n': 1902779,
              'o': 37.45,
              't': 1667275200000,
              'v': 136357976.0,
              'vw': 33.3457}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '39117b45ae2317284d8c96bce16afa5f',
 'results': [{'c': 27.64,
              'h': 41.4399,
              'l': 25.451,
              'n': 1716758,
              'o': 28.62,
              't': 1672549200000,
              'v': 125211410.0,
              'vw': 31.9529}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'd6642b591c4e06db8fed635db90b2c96',
 'results': [{'c': 28.93,
              'h': 41.4399,
              'l': 25.451,
              'n': 1538338,
              'o': 38.09,
              't': 1675227600000,
              'v': 111463688.0,
              'vw': 31.2882}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '930e7ffbc294a8bfe36c362f27a33a23',
 'results': [{'c': 30.68,
              'h': 35.18,
              'l': 25.451,
              'n': 1556183,
              'o': 33.3,
              't': 1677646800000,
              'v': 111888538.0,
              'vw': 30.1497}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'd3d4bcce44a2175833e9fbf13b28423e',
 'results': [{'c': 23.69,
              'h': 35.09,
              'l': 23.4,
              'n': 1662558,
              'o': 31.64,
              't': 1680321600000,
              'v': 122548680.0,
              'vw': 29.1739}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'c2858ee3472d029fdd61ffce299069d0',
 'results': [{'c': 25.4,
              'h': 35.09,
              'l': 22.665,
              'n': 1722611,
              'o': 31.34,
              't': 1682913600000,
              'v': 127968105.0,
              'vw': 28.1714}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 106,
 'request_id': '5844d28cc3d48d7996f749f8624e257a',
 'results': [{'c': 24.5404,
              'h': 35.09,
              'l': 22.665,
              'n': 1439920,
              'o': 28.24,
              't': 1685592000000,
              'v': 106497132.0,
              'vw': 27.8064}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 85,
 'request_id': '25c299ff13fe4c56dfa91817a3670629',
 'results': [{'c': 24.56,
              'h': 35.09,
              'l': 22.665,
              'n': 1224724,
              'o': 28.42,
              't': 1688184000000,
              'v': 91515068.0,
              'vw': 27.7081}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 65,
 'request_id': 'afa5e416d6ff54f889ceb9dc89924c17',
 'results': [{'c': 24.56,
              'h': 35.09,
              'l': 22.665,
              'n': 1036411,
              'o': 30.51,
              't': 1690862400000,
              'v': 78488550.0,
              'vw': 27.4414}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}

-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 42,
 'request_id': '446ce83808e568aa1b4897ed10e9ae87',
 'results': [{'c': 24.56,
              'h': 29.8299,
              'l': 22.665,
              'n': 670044,
              'o': 29.72,
              't': 1693540800000,
              'v': 51496210.0,
              'vw': 25.3999}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 22,
 'request_id': 'c630091eb2015ab685f5c665338520d6',
 'results': [{'c': 24.56,
              'h': 26.43,
              'l': 22.85,
              'n': 285501,
              'o': 23.14,
              't': 1696132800000,
              'v': 20423503.0,
              'vw': 24.7228}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Now Finding: SBUX
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '3c0c1c81183dd0935af6619934d7df45',
 'results': [{'c': 77.92,
              'h': 117.8,
              'l': 77.7808,
              'n': 13062723,
              'o': 107.225,
              't': 1635739200000,
              'v': 1078291028.0,
              'vw': 97.565}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '928b78ecea34bb377f8e67293d71a792',
 'results': [{'c': 78.11,
              'h': 117.8,
              'l': 68.39,
              'n': 14543812,
              'o': 116.47,
              't': 1641013200000,
              'v': 1268762799.0,
              'vw': 85.3797}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'b9039abc9ada738d57a1fb848b526bbc',
 'results': [{'c': 81.5,
              'h': 99.15,
              'l': 68.39,
              'n': 13518774,
              'o': 98.4175,
              't': 1643691600000,
              'v': 1173504972.0,
              'vw': 81.7601}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5ecbe9071a4b83669bd5e94809ae3f4e',
 'results': [{'c': 86.92,
              'h': 93.5,
              'l': 68.39,
              'n': 12863680,
              'o': 91.49,
              't': 1646110800000,
              'v': 1121522615.0,
              'vw': 80.3283}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'f8185bf167f4f979ab2ee4d18cc704d7',
 'results': [{'c': 84.7,
              'h': 93.48,
              'l': 68.39,
              'n': 12344026,
              'o': 91.5,
              't': 1648785600000,
              'v': 1073685684.0,
              'vw': 80.1503}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5a2728d3097d6d3b8ef500d86a216ca8',
 'results': [{'c': 86.79,
              'h': 93.48,
              'l': 68.39,
              'n': 11621839,
              'o': 75.25,
              't': 1651377600000,
              'v': 1011212382.0,
              'vw': 80.8995}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '9612bab9c9a8b58e0cbeb07ed5c84297',
 'results': [{'c': 97.95,
              'h': 99.53,
              'l': 70.35,
              'n': 10737688,
              'o': 78.75,
              't': 1654056000000,
              'v': 909939770.0,
              'vw': 84.8653}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'e8cfccbbfece035d5439ea04eef8851e',
 'results': [{'c': 98,
              'h': 105.54,
              'l': 75.73,
              'n': 10429808,
              'o': 76.73,
              't': 1656648000000,
              'v': 872180575.0,
              'vw': 89.3456}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'ff125419d3eb02856f23cbcb6eaee935',
 'results': [{'c': 105.04,
              'h': 107.595,
              'l': 81.67,
              'n': 10561846,
              'o': 84.19,
              't': 1659326400000,
              'v': 869370843.0,
              'vw': 92.3842}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1fcdfe82968cfbc055a49f7e86146495',
 'results': [{'c': 103.51,
              'h': 110.83,
              'l': 81.67,
              'n': 10929106,
              'o': 83.7,
              't': 1662004800000,
              'v': 889318807.0,
              'vw': 95.7439}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '53b789050a5c4d4d5a54b1cb20a55c27',
 'results': [{'c': 98.34,
              'h': 110.83,
              'l': 82.43,
              'n': 10368190,
              'o': 84.75,
              't': 1664596800000,
              'v': 807709929.0,
              'vw': 98.4406}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '9ebc61a9ca37a479579f01dca5a63f4f',
 'results': [{'c': 109.34,
              'h': 111.11,
              'l': 82.97,
              'n': 10264416,
              'o': 88.06,
              't': 1667275200000,
              'v': 751122676.0,
              'vw': 101.7863}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'e952642421643f8f669be565f2c6774e',
 'results': [{'c': 98.23,
              'h': 115.48,
              'l': 96.52,
              'n': 11557334,
              'o': 100.56,
              't': 1672549200000,
              'v': 765299042.0,
              'vw': 103.9128}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'e40e84da632c8a670bd3145e3d671dee',
 'results': [{'c': 102.92,
              'h': 115.48,
              'l': 95.55,
              'n': 11956655,
              'o': 108.97,
              't': 1675227600000,
              'v': 767616004.0,
              'vw': 102.9306}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'b27196115f1daa9be86b1c116533a7c9',
 'results': [{'c': 96.46,
              'h': 115.48,
              'l': 95.55,
              'n': 12161541,
              'o': 102.19,
              't': 1677646800000,
              'v': 748323896.0,
              'vw': 102.1521}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '946f39f396b339abe8751753b78c6299',
 'results': [{'c': 93.68,
              'h': 115.48,
              'l': 93.03,
              'n': 12293019,
              'o': 104.06,
              't': 1680321600000,
              'v': 748114848.0,
              'vw': 101.3726}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}

-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '6f6cdacaba610ed64d46a1e72bec6999',
 'results': [{'c': 94.42,
              'h': 115.48,
              'l': 89.21,
              'n': 12317927,
              'o': 114.252,
              't': 1682913600000,
              'v': 757633509.0,
              'vw': 99.2158}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 106,
 'request_id': '5acb551e14a4ffafc310eea495b17192',
 'results': [{'c': 92.93,
              'h': 104.46,
              'l': 89.21,
              'n': 10522510,
              'o': 97.59,
              't': 1685592000000,
              'v': 645357992.0,
              'vw': 97.5282}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 85,
 'request_id': 'a26bfb73484713f4df328619f1c6b80f',
 'results': [{'c': 92.98,
              'h': 104.46,
              'l': 89.21,
              'n': 8240383,
              'o': 98.73,
              't': 1688184000000,
              'v': 494480209.0,
              'vw': 96.9856}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 65,
 'request_id': 'f2fecfc09b79f71ce7651e32a7444d65',
 'results': [{'c': 92.98,
              'h': 104.46,
              'l': 89.21,
              'n': 6162776,
              'o': 101.47,
              't': 1690862400000,
              'v': 363135876.0,
              'vw': 95.6412}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 42,
 'request_id': 'f15f9d13c704e33250d0b5c148ba21f1',
 'results': [{'c': 92.98,
              'h': 98.75,
              'l': 89.21,
              'n': 3929760,
              'o': 98.4,
              't': 1693540800000,
              'v': 236096045.0,
              'vw': 93.7499}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 22,
 'request_id': 'e3e9d814f944f0614dee574cf62003e3',
 'results': [{'c': 92.98,
              'h': 95.66,
              'l': 89.21,
              'n': 2092880,
              'o': 91.05,
              't': 1696132800000,
              'v': 122965356.0,
              'vw': 92.7566}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Done!
-------------------------

In [7]:
#Create dataframe
df = pd.DataFrame(data_list)
df.head()

,ticker,queryCount,resultsCount,adjusted,results,status,request_id,count
0,BUD,120,1,True,"[{'v': 195949135.0, 'vw': 59.8907, 'o': 60.21,...",OK,b5296d2db4a3778378bc3a94ba2df909,1
1,BUD,120,1,True,"[{'v': 185073263.0, 'vw': 58.7384, 'o': 62.43,...",OK,8c6bd9f935f6a89995d0f4551039be15,1
2,BUD,120,1,True,"[{'v': 176759102.0, 'vw': 57.2436, 'o': 64.01,...",OK,5a5d15c0045763f5d765121a09700063,1
3,BUD,120,1,True,"[{'v': 177299717.0, 'vw': 55.898, 'o': 59.94, ...",OK,44676d9f0cfef0282f5f2c6f2bcb85f8,1
4,BUD,120,1,True,"[{'v': 160603099.0, 'vw': 54.0878, 'o': 60.79,...",OK,00d49fdea0a81c54f219ab93a0bbee23,1

In [14]:
#Clean the dataframe
cleandf = df.loc[:, ['ticker', 'results']]
cleandf

    ticker                                            results
0      BUD  [{'v': 195949135.0, 'vw': 59.8907, 'o': 60.21,...
1      BUD  [{'v': 185073263.0, 'vw': 58.7384, 'o': 62.43,...
2      BUD  [{'v': 176759102.0, 'vw': 57.2436, 'o': 64.01,...
3      BUD  [{'v': 177299717.0, 'vw': 55.898, 'o': 59.94, ...
4      BUD  [{'v': 160603099.0, 'vw': 54.0878, 'o': 60.79,...
..     ...                                                ...
127   SBUX  [{'v': 645357992.0, 'vw': 97.5282, 'o': 97.59,...
128   SBUX  [{'v': 494480209.0, 'vw': 96.9856, 'o': 98.73,...
129   SBUX  [{'v': 363135876.0, 'vw': 95.6412, 'o': 101.47...
130   SBUX  [{'v': 236096045.0, 'vw': 93.7499, 'o': 98.4, ...
131   SBUX  [{'v': 122965356.0, 'vw': 92.7566, 'o': 91.05,...

[132 rows x 2 columns]

In [19]:
#Parse the results data
df_new = cleandf.explode('results')
def break_up_dictionary(row):
    results = row['results'][0]
    for key, value in results.items():
        row[key] = value
    return row

df_new = cleandf.apply(break_up_dictionary, axis=1)
df_new=df_new

,ticker,results,v,vw,o,c,h,l,t,n
0,BUD,"[{'v': 195949135.0, 'vw': 59.8907, 'o': 60.21,...",195949135.0,59.8907,60.21,59.31,67.91,52.65,1635739200000,1957405
1,BUD,"[{'v': 185073263.0, 'vw': 58.7384, 'o': 62.43,...",185073263.0,58.7384,62.43,53.94,67.91,50.59,1641013200000,2105726
2,BUD,"[{'v': 176759102.0, 'vw': 57.2436, 'o': 64.01,...",176759102.0,57.2436,64.01,55.02,66.05,50.59,1643691600000,2060645
3,BUD,"[{'v': 177299717.0, 'vw': 55.898, 'o': 59.94, ...",177299717.0,55.8980,59.94,52.51,63.45,50.59,1646110800000,2053783
4,BUD,"[{'v': 160603099.0, 'vw': 54.0878, 'o': 60.79,...",160603099.0,54.0878,60.79,48.57,63.45,47.23,1648785600000,1951050
...,...,...,...,...,...,...,...,...,...,...
127,SBUX,"[{'v': 645357992.0, 'vw': 97.5282, 'o': 97.59,...",645357992.0,97.5282,97.59,92.93,104.46,89.21,1685592000000,10522510
128,SBUX,"[{'v': 494480209.0, 'vw': 96.9856, 'o': 98.73,...",494480209.0,96.9856,98.73,92.98,104.46,89.21,1688184000000,8240383
129,SBUX,"[{'v': 363135876.0, 'vw': 95.6412, 'o': 101.47...",363135876.0,95.6412,101.47,92.98,104.46,89.21,1690862400000,6162776
130,SBUX,"[{'v': 236096045.0, 'vw': 93.7499, 'o': 98.4, ...",236096045.0,93.7499,98.40,92.98,98.75,89.21,1693540800000,3929760
131,SBUX,"[{'v': 122965356.0, 'vw': 92.7566, 'o': 91.05,...",122965356.0,92.7566,91.05,92.98,95.66,89.21,1696132800000,2092880

In [ ]:
#Save data to csv
df.to_csv('data.csv', index=True)