In [1]:
#First, imports
import time 
import requests
import json
import csv
import pprint
import pandas as pd
from Config import apikey

In [5]:
#Start by accessing api
base_url=f"https://api.polygon.io/v2/aggs/ticker/"
#Beer=BUDweiser and coors(TAP), Soda=COKE and PEPsi, Coffee=dutchBROS and StarBUX 
tickers=["BUD","TAP","KO","PEP","BROS","SBUX"]
data_list=[]

In [6]:
def iterate_months():
    start_month = 11
    for year in range(2021, 2024):
        for month in range(start_month, 12):
            yield f"{year}-{month:02d}-01"
        start_month = 1

In [7]:
#Responses in following string
# C- Close price                # O- Open price  
# H- High price                 # T- Unix time
# L- Low price                  # V- Volume
# N- Number of transactions     # VW- Volume weighted

In [9]:
#Gather data and append to a list
for tick in tickers:
    
    #Makes the print a little prettier
    print("-------------------------")
    print(f"Now Finding: {tick}")
    print("-------------------------")
    
    #Iterate, find and append data
    for month in iterate_months():
        
        #Shows the date time
        print("-------------------------")
        print(f"Result Date: {month}")
        print("-------------------------")
        
        full_url=base_url+f"{tick}/range/12/month/{month}/{month}?adjusted=true&sort=asc&limit=120&apiKey={apikey}"
        data = requests.get(full_url)
        data_json = data.json()
        formatted_data = pprint.pformat(data_json)
        print(formatted_data)
        data_list.append(data_json)
        
        #limited to 5 pulls per miniute, timer allows for the sixth call
        time.sleep(13)
        
        #Stop on todays date
        if month == "2023-11-02":
            break 
    
#Quality of life to say when its done
print("-------------------------")
print(f"Done!")
print("-------------------------")

-------------------------
Now Finding: BUD
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'message': "Your plan doesn't include this data timeframe. Please upgrade "
            'your plan at https://polygon.io/pricing',
 'request_id': '1f171486e28989049d930ad5f0f1f8cd',
 'status': 'NOT_AUTHORIZED'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'c3fbad86030c8755e1fcd35751491c70',
 'results': [{'c': 53.94,
              'h': 67.91,
              'l': 50.59,
              'n': 2105726,
              'o': 62.43,
              't': 1641013200000,
              'v': 185073263.0,
              'vw': 58.7384}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'a9420ea938d4c9c4836fc3157b7ca229',
 'results': [{'c': 55.02,
              'h': 66.05,
              'l': 50.59,
              'n': 2060645,
              'o': 64.01,
              't': 1643691600000,
              'v': 176759102.0,
              'vw': 57.2436}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '0650ca463b969aade0c1e11e2bd3f9df',
 'results': [{'c': 52.51,
              'h': 63.45,
              'l': 50.59,
              'n': 2053783,
              'o': 59.94,
              't': 1646110800000,
              'v': 177299717.0,
              'vw': 55.898}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '72b5b54d6d6da75e1e9860fe47695624',
 'results': [{'c': 48.57,
              'h': 63.45,
              'l': 47.23,
              'n': 1951050,
              'o': 60.79,
              't': 1648785600000,
              'v': 160603099.0,
              'vw': 54.0878}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '73e196e879780bd5354e753148004fa3',
 'results': [{'c': 45.23,
              'h': 58.37,
              'l': 44.51,
              'n': 2004952,
              'o': 56.98,
              't': 1651377600000,
              'v': 170988591.0,
              'vw': 51.7573}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '71c86db8d83cc22309409b7beb2e2fde',
 'results': [{'c': 55.53,
              'h': 56.59,
              'l': 44.51,
              'n': 2015899,
              'o': 56.4,
              't': 1654056000000,
              'v': 172949903.0,
              'vw': 50.9943}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '96f7e76222ef01fef35173ebf4495e74',
 'results': [{'c': 59.37,
              'h': 61.63,
              'l': 44.51,
              'n': 1912934,
              'o': 53.92,
              't': 1656648000000,
              'v': 165669941.0,
              'vw': 51.654}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '896937a4ea78c3804fae00dc4cb2163f',
 'results': [{'c': 59.8,
              'h': 61.89,
              'l': 44.51,
              'n': 1925862,
              'o': 53,
              't': 1659326400000,
              'v': 166972811.0,
              'vw': 52.6036}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1b24f6645453774d4cdf2dd52f7e5aa1',
 'results': [{'c': 60.79,
              'h': 61.89,
              'l': 44.51,
              'n': 1955362,
              'o': 47.47,
              't': 1662004800000,
              'v': 165184132.0,
              'vw': 53.8958}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'ad5ac14b474a1bcf17475d3b2a126fe3',
 'results': [{'c': 62.18,
              'h': 62.53,
              'l': 44.51,
              'n': 2075917,
              'o': 44.99,
              't': 1664596800000,
              'v': 169385926.0,
              'vw': 56.4788}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '820fbe32b635376dc5bcb51f9f9430ca',
 'results': [{'c': 65.65,
              'h': 67.09,
              'l': 48.685,
              'n': 2286932,
              'o': 51.44,
              't': 1667275200000,
              'v': 190980699.0,
              'vw': 60.6309}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '68ccfcfbc248a9f2e984b1fefbf1eb2c',
 'results': [{'c': 56.36,
              'h': 67.09,
              'l': 52.93,
              'n': 3015781,
              'o': 60.31,
              't': 1672549200000,
              'v': 255697533.0,
              'vw': 60.4331}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '943f6267a66fa1d39a725cb34134fe75',
 'results': [{'c': 58.56,
              'h': 67.09,
              'l': 52.93,
              'n': 3082445,
              'o': 60.66,
              't': 1675227600000,
              'v': 263647158.0,
              'vw': 60.0174}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'e03159c15e613e0dc617b3d2afab9cee',
 'results': [{'c': 56.2,
              'h': 67.09,
              'l': 52.93,
              'n': 3223618,
              'o': 61.2,
              't': 1677646800000,
              'v': 282078590.0,
              'vw': 59.5769}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '44afd456710155b254763a71e8016723',
 'results': [{'c': 56.44,
              'h': 67.01,
              'l': 52.93,
              'n': 3239070,
              'o': 66.52,
              't': 1680321600000,
              'v': 282846458.0,
              'vw': 58.8888}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'db3cca6e6a1b71126247eab4dc6806c8',
 'results': [{'c': 53.28,
              'h': 66.32,
              'l': 51.66,
              'n': 3257020,
              'o': 65.11,
              't': 1682913600000,
              'v': 275081831.0,
              'vw': 56.8354}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 108,
 'request_id': '0b12683d893835efc741fab0c746dceb',
 'results': [{'c': 58.13,
              'h': 59.21,
              'l': 51.66,
              'n': 2842648,
              'o': 53.71,
              't': 1685592000000,
              'v': 241442337.0,
              'vw': 55.8711}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}

-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 87,
 'request_id': '8aa9002d160b361f0763326c162a1fe3',
 'results': [{'c': 58.13,
              'h': 59.21,
              'l': 51.66,
              'n': 2189969,
              'o': 57,
              't': 1688184000000,
              'v': 182319103.0,
              'vw': 55.8576}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 67,
 'request_id': '37f2d82043e38adda6874d14aea3cae2',
 'results': [{'c': 58.13,
              'h': 58.28,
              'l': 51.66,
              'n': 1770205,
              'o': 57.15,
              't': 1690862400000,
              'v': 142580502.0,
              'vw': 55.3466}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 44,
 'request_id': '1644fbf138b9619b803a39b714ca7a97',
 'results': [{'c': 58.13,
              'h': 58.2,
              'l': 51.66,
              'n': 1223840,
              'o': 56.91,
              't': 1693540800000,
              'v': 96087742.0,
              'vw': 54.7653}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 24,
 'request_id': 'ad21f996f7869ee95dde7d7350c45f9a',
 'results': [{'c': 58.13,
              'h': 58.2,
              'l': 51.66,
              'n': 745318,
              'o': 54.51,
              't': 1696132800000,
              'v': 58884112.0,
              'vw': 53.913}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Result Date: 2023-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 2,
 'request_id': 'a859daa609fe1bd738db756b0c253766',
 'results': [{'c': 58.13,
              'h': 58.2,
              'l': 56.015,
              'n': 78119,
              'o': 56.43,
              't': 1698811200000,
              'v': 5863473.0,
              'vw': 57.0129}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BUD'}
-------------------------
Now Finding: TAP
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'message': "Your plan doesn't include this data timeframe. Please upgrade "
            'your plan at https://polygon.io/pricing',
 'request_id': '59bf457bf4d1cdaebc8cf0be4751a47b',
 'status': 'NOT_AUTHORIZED'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '72818b1c283c892cbb164069d29aae30',
 'results': [{'c': 55.77,
              'h': 57.45,
              'l': 46.47,
              'n': 2422641,
              'o': 46.54,
              't': 1641013200000,
              'v': 194100944.0,
              'vw': 51.7757}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4a2f5c082d0f11af6b7d8486f26d982e',
 'results': [{'c': 58.22,
              'h': 59.38,
              'l': 47.34,
              'n': 2409340,
              'o': 47.58,
              't': 1643691600000,
              'v': 189620132.0,
              'vw': 53.0272}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '552f8f7644654bc7b9384f28a9fd91bc',
 'results': [{'c': 56.09,
              'h': 60.12,
              'l': 49.12,
              'n': 2434905,
              'o': 51.76,
              't': 1646110800000,
              'v': 188182783.0,
              'vw': 54.1061}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'df4dfe638f40b582bdb3f76ebd736022',
 'results': [{'c': 49.15,
              'h': 60.12,
              'l': 49.1,
              'n': 2372252,
              'o': 53.39,
              't': 1648785600000,
              'v': 177858495.0,
              'vw': 54.2744}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'd0781d3f2b8f757e0c0869898d724d2f',
 'results': [{'c': 48.24,
              'h': 60.12,
              'l': 46.685,
              'n': 2345719,
              'o': 54.52,
              't': 1651377600000,
              'v': 173785804.0,
              'vw': 53.5571}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5bdb45235694226e19f6f5cfc02b1d98',
 'results': [{'c': 53.5,
              'h': 60.12,
              'l': 46.685,
              'n': 2286420,
              'o': 55.98,
              't': 1654056000000,
              'v': 164117982.0,
              'vw': 52.9584}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '60e34da3e4fdb0e61d8cc97e8958d5ea',
 'results': [{'c': 50.77,
              'h': 60.12,
              'l': 46.685,
              'n': 2250213,
              'o': 54.48,
              't': 1656648000000,
              'v': 159448782.0,
              'vw': 53.0197}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4c83c2dd1ae8842e7e70de676b9d77d0',
 'results': [{'c': 49.98,
              'h': 60.12,
              'l': 46.685,
              'n': 2218999,
              'o': 59.49,
              't': 1659326400000,
              'v': 153933353.0,
              'vw': 51.7091}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '46bba63c6fe7574baf950de1603cd836',
 'results': [{'c': 53.5,
              'h': 56.28,
              'l': 46.685,
              'n': 2293933,
              'o': 50.96,
              't': 1662004800000,
              'v': 158599886.0,
              'vw': 51.2054}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'adb5b1af829da5eb8253f7fff015395e',
 'results': [{'c': 50.7,
              'h': 56.28,
              'l': 46.685,
              'n': 2453742,
              'o': 48.29,
              't': 1664596800000,
              'v': 170836918.0,
              'vw': 51.626}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '51b9988ada3ae19f5dce0d12442c2b30',
 'results': [{'c': 58.71,
              'h': 59.26,
              'l': 46.9,
              'n': 2632656,
              'o': 50.35,
              't': 1667275200000,
              'v': 185506016.0,
              'vw': 52.6181}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '31287eec123f86e684373b7fcf1920a5',
 'results': [{'c': 65.67,
              'h': 68.13,
              'l': 48.485,
              'n': 3218355,
              'o': 50.55,
              't': 1672549200000,
              'v': 240311486.0,
              'vw': 57.69}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}

-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '22f71aa2af30d5ee45eec33940f0dd98',
 'results': [{'c': 70.67,
              'h': 70.7382,
              'l': 49.32,
              'n': 3287014,
              'o': 52.4,
              't': 1675227600000,
              'v': 247607380.0,
              'vw': 60.0345}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'b24a8df677aef76403296aa5d9e89831',
 'results': [{'c': 62.78,
              'h': 70.9,
              'l': 49.32,
              'n': 3405737,
              'o': 52.88,
              't': 1677646800000,
              'v': 255480911.0,
              'vw': 61.9304}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'dd6aa834419bb5561e2ec4dfac5869a8',
 'results': [{'c': 63.4,
              'h': 70.9,
              'l': 51.45,
              'n': 3326555,
              'o': 51.81,
              't': 1680321600000,
              'v': 247201745.0,
              'vw': 63.7097}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'ed3144af9d04ef17c1ff59145bb46c61',
 'results': [{'c': 58.34,
              'h': 70.9,
              'l': 57.34,
              'n': 3296120,
              'o': 59.47,
              't': 1682913600000,
              'v': 242219431.0,
              'vw': 64.4123}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 108,
 'request_id': '5d2567a6708d36733853303b226748ab',
 'results': [{'c': 57.83,
              'h': 70.9,
              'l': 55.665,
              'n': 2821111,
              'o': 61.51,
              't': 1685592000000,
              'v': 199960555.0,
              'vw': 64.1773}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 87,
 'request_id': '56a6713d7bfc738c92010bbeeb1f69f4',
 'results': [{'c': 57.83,
              'h': 70.9,
              'l': 55.665,
              'n': 2208256,
              'o': 65.64,
              't': 1688184000000,
              'v': 152365075.0,
              'vw': 63.6668}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 67,
 'request_id': '97db37a9da6672ed643d25d613a4c7e2',
 'results': [{'c': 57.83,
              'h': 68.64,
              'l': 55.665,
              'n': 1687217,
              'o': 65.15,
              't': 1690862400000,
              'v': 110514158.0,
              'vw': 62.1004}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 44,
 'request_id': 'b311e9941689c8865c8a0c38faeb7ed1',
 'results': [{'c': 57.83,
              'h': 65.31,
              'l': 55.665,
              'n': 1084583,
              'o': 63.57,
              't': 1693540800000,
              'v': 70169325.0,
              'vw': 60.7228}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 24,
 'request_id': 'e7a9b091b0f44826a2375e674335fa3e',
 'results': [{'c': 57.83,
              'h': 63.84,
              'l': 55.665,
              'n': 666661,
              'o': 63.52,
              't': 1696132800000,
              'v': 42759211.0,
              'vw': 58.9699}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Result Date: 2023-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 2,
 'request_id': 'a765972bf9b83cf24f00b78d4a2307aa',
 'results': [{'c': 57.83,
              'h': 59.01,
              'l': 55.665,
              'n': 91468,
              'o': 57.91,
              't': 1698811200000,
              'v': 6114926.0,
              'vw': 57.6662}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'TAP'}
-------------------------
Now Finding: KO
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'message': "Your plan doesn't include this data timeframe. Please upgrade "
            'your plan at https://polygon.io/pricing',
 'request_id': 'c1dcc1eebdaaf7e091b08f4aca8cf38f',
 'status': 'NOT_AUTHORIZED'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '759d67ddc571cdb5c76cd87f93ac1853',
 'results': [{'c': 63.04,
              'h': 67.2,
              'l': 57.5,
              'n': 16111650,
              'o': 58.82,
              't': 1641013200000,
              'v': 2310556768.0,
              'vw': 61.9102}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'b2877665d599d1123c7eccf9254d19ec',
 'results': [{'c': 62.19,
              'h': 67.2,
              'l': 57.5,
              'n': 15725686,
              'o': 60.91,
              't': 1643691600000,
              'v': 2174518278.0,
              'vw': 62.2863}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'badb48883b296e681f9d9ad4bc323d60',
 'results': [{'c': 65.17,
              'h': 67.2,
              'l': 57.5,
              'n': 14966494,
              'o': 62.14,
              't': 1646110800000,
              'v': 1983913654.0,
              'vw': 62.6321}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '2bf671f37e8deee1c70c7d6d76ade2ad',
 'results': [{'c': 59.26,
              'h': 67.2,
              'l': 58.2528,
              'n': 14560919,
              'o': 62.33,
              't': 1648785600000,
              'v': 1839667066.0,
              'vw': 62.9605}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'bbc70b66e687a6117d2b824968bcefff',
 'results': [{'c': 55.08,
              'h': 66.38,
              'l': 54.015,
              'n': 14869405,
              'o': 65.28,
              't': 1651377600000,
              'v': 1835485185.0,
              'vw': 61.492}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1f3374e654e0bf4920eb532962475d30',
 'results': [{'c': 61.14,
              'h': 65.47,
              'l': 54.015,
              'n': 13991618,
              'o': 63.42,
              't': 1654056000000,
              'v': 1670084670.0,
              'vw': 60.5835}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '205c701d8b3c4b1ed82086ee94a04b49',
 'results': [{'c': 62.79,
              'h': 65.47,
              'l': 54.015,
              'n': 13465903,
              'o': 63.12,
              't': 1656648000000,
              'v': 1602567809.0,
              'vw': 60.8357}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}

-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5710cbdeddddbdd56d706a6a2b29b693',
 'results': [{'c': 60.08,
              'h': 65.47,
              'l': 54.015,
              'n': 13269955,
              'o': 64.09,
              't': 1659326400000,
              'v': 1553465523.0,
              'vw': 60.6819}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1b5b0f1c0e47b6bcfac53288168ea170',
 'results': [{'c': 60.09,
              'h': 64.7,
              'l': 54.015,
              'n': 13893370,
              'o': 61.58,
              't': 1662004800000,
              'v': 1651012999.0,
              'vw': 60.164}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '7b9cb2d27f3b5589138f7631a4601841',
 'results': [{'c': 60.9,
              'h': 64.7,
              'l': 54.015,
              'n': 13756416,
              'o': 56.36,
              't': 1664596800000,
              'v': 1646131054.0,
              'vw': 60.2293}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'e799861173ca27ea719a2fdd926e1fa7',
 'results': [{'c': 63.85,
              'h': 64.99,
              'l': 58.1,
              'n': 13146524,
              'o': 60.03,
              't': 1667275200000,
              'v': 1550272808.0,
              'vw': 61.3439}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5c3a23b89fbdc027cf093126be592bc6',
 'results': [{'c': 61.22,
              'h': 64.99,
              'l': 58.37,
              'n': 14249892,
              'o': 63.56,
              't': 1672549200000,
              'v': 1634039587.0,
              'vw': 61.1816}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '3f0904bd19aff2bc741da9436b44b2e6',
 'results': [{'c': 62.25,
              'h': 64.99,
              'l': 58.37,
              'n': 14654206,
              'o': 61.14,
              't': 1675227600000,
              'v': 1632776727.0,
              'vw': 61.094}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'eeb686244425327c8c5ab61c7410b1a9',
 'results': [{'c': 60.43,
              'h': 64.99,
              'l': 58.37,
              'n': 14506154,
              'o': 59.13,
              't': 1677646800000,
              'v': 1553305188.0,
              'vw': 61.3419}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '99dc7893d55b1a98716c17772bada138',
 'results': [{'c': 57.6,
              'h': 64.99,
              'l': 57.42,
              'n': 14587820,
              'o': 62.3,
              't': 1680321600000,
              'v': 1538179134.0,
              'vw': 61.0392}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1104a9923c98f9b3ccc81ac2938d5e58',
 'results': [{'c': 54.35,
              'h': 64.69,
              'l': 51.55,
              'n': 15522425,
              'o': 64.15,
              't': 1682913600000,
              'v': 1634416041.0,
              'vw': 59.4361}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 108,
 'request_id': '1f58bd0ebde28fabf7f9045c56da1f79',
 'results': [{'c': 57.09,
              'h': 63.265,
              'l': 51.55,
              'n': 14451639,
              'o': 59.94,
              't': 1685592000000,
              'v': 1506258667.0,
              'vw': 58.5226}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 87,
 'request_id': '0663de8987731f7d9e0915b452cbde2d',
 'results': [{'c': 57.09,
              'h': 63.265,
              'l': 51.55,
              'n': 11677506,
              'o': 60.2,
              't': 1688184000000,
              'v': 1185813788.0,
              'vw': 57.899}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 67,
 'request_id': '3a5f6fbfb9212a7b2958c7039085ad65',
 'results': [{'c': 57.09,
              'h': 62.585,
              'l': 51.55,
              'n': 9091308,
              'o': 62.09,
              't': 1690862400000,
              'v': 929505384.0,
              'vw': 57.0004}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 44,
 'request_id': '01f05ef79623c74f2d9bcf75c51d64ad',
 'results': [{'c': 57.09,
              'h': 60.13,
              'l': 51.55,
              'n': 6708120,
              'o': 60,
              't': 1693540800000,
              'v': 725168546.0,
              'vw': 55.9281}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 24,
 'request_id': '7528e53454040a69af284f07fe141eb5',
 'results': [{'c': 57.09,
              'h': 57.15,
              'l': 51.55,
              'n': 4031927,
              'o': 55.91,
              't': 1696132800000,
              'v': 415055728.0,
              'vw': 54.4523}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Result Date: 2023-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 2,
 'request_id': '9f77b551917d9547f6c1e0482191482f',
 'results': [{'c': 57.09,
              'h': 57.15,
              'l': 56.26,
              'n': 282573,
              'o': 56.8,
              't': 1698811200000,
              'v': 27198034.0,
              'vw': 56.7206}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'KO'}
-------------------------
Now Finding: PEP
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'message': "Your plan doesn't include this data timeframe. Please upgrade "
            'your plan at https://polygon.io/pricing',
 'request_id': '807797f5da273a1d451c0bd6383c8d44',
 'status': 'NOT_AUTHORIZED'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '45e93539974e49c077c6feee7e0155f2',
 'results': [{'c': 166.13,
              'h': 177.62,
              'l': 153.37,
              'n': 8689823,
              'o': 172.2,
              't': 1641013200000,
              'v': 677766860.0,
              'vw': 167.9066}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'f7fe21860bb058643d5e19357da80b2b',
 'results': [{'c': 169.85,
              'h': 177.62,
              'l': 153.37,
              'n': 8441179,
              'o': 173.15,
              't': 1643691600000,
              'v': 645532362.0,
              'vw': 167.0945}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}

-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '8dfa11e4a11653dac91b49e87ee3e5d3',
 'results': [{'c': 180.17,
              'h': 181.07,
              'l': 153.37,
              'n': 7970061,
              'o': 163.07,
              't': 1646110800000,
              'v': 598254882.0,
              'vw': 167.8107}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5955ecda3ce83cc0615d2edece77cce4',
 'results': [{'c': 168.6,
              'h': 181.07,
              'l': 154.8576,
              'n': 7781960,
              'o': 167.89,
              't': 1648785600000,
              'v': 584754701.0,
              'vw': 169.8246}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '16f8a7f300b579a3401bb021c1835ead',
 'results': [{'c': 171.46,
              'h': 181.07,
              'l': 154.8576,
              'n': 7965519,
              'o': 172.995,
              't': 1651377600000,
              'v': 600179237.0,
              'vw': 169.0204}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4eb318ee2b6639bdc2e9fc228582d913',
 'results': [{'c': 181.33,
              'h': 183.58,
              'l': 154.8576,
              'n': 7738471,
              'o': 168.18,
              't': 1654056000000,
              'v': 569558724.0,
              'vw': 170.8474}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '5cd3b2ec0389a1ccde4935a76a1eae49',
 'results': [{'c': 181.23,
              'h': 186.84,
              'l': 160.98,
              'n': 7574118,
              'o': 166.74,
              't': 1656648000000,
              'v': 566890459.0,
              'vw': 174.7018}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'c4e81f7144f5a72119cbb168f95800a0',
 'results': [{'c': 169.88,
              'h': 186.84,
              'l': 160.98,
              'n': 7600312,
              'o': 174.55,
              't': 1659326400000,
              'v': 565165245.0,
              'vw': 175.7339}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'bdcb59a199cc65d969a6331bc430de12',
 'results': [{'c': 176.31,
              'h': 186.84,
              'l': 160.98,
              'n': 8083268,
              'o': 170.9201,
              't': 1662004800000,
              'v': 601469619.0,
              'vw': 175.0036}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '405ac3094ff0adaeb298a60f47cf0e7a',
 'results': [{'c': 179.09,
              'h': 186.84,
              'l': 160.98,
              'n': 8051825,
              'o': 163.52,
              't': 1664596800000,
              'v': 586966686.0,
              'vw': 176.1001}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4c418095475c168bed70e53d1cc3e9d3',
 'results': [{'c': 189.71,
              'h': 190.18,
              'l': 167.05,
              'n': 7671600,
              'o': 180.94,
              't': 1667275200000,
              'v': 546772075.0,
              'vw': 178.0092}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '92849121afb693f67d4cae2378b3a822',
 'results': [{'c': 184.89,
              'h': 196.88,
              'l': 167.05,
              'n': 7724140,
              'o': 180.59,
              't': 1672549200000,
              'v': 544020091.0,
              'vw': 179.9529}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '7ee01dc0b5b38908765e8af028fb3f07',
 'results': [{'c': 191.36,
              'h': 196.88,
              'l': 167.05,
              'n': 8037588,
              'o': 170.88,
              't': 1675227600000,
              'v': 567840657.0,
              'vw': 182.2497}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'bba8491ad4d74bb26a2d2bfce4354099',
 'results': [{'c': 177.05,
              'h': 196.88,
              'l': 169.12,
              'n': 7991935,
              'o': 172.32,
              't': 1677646800000,
              'v': 548298615.0,
              'vw': 184.1244}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '7978bf71470fdaae3dd39bbe5e233aca',
 'results': [{'c': 175.27,
              'h': 196.88,
              'l': 173.48,
              'n': 8105101,
              'o': 181.9,
              't': 1680321600000,
              'v': 546540307.0,
              'vw': 184.5972}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'efcb3f119872f8cf5d39c346720c41d6',
 'results': [{'c': 160.56,
              'h': 196.88,
              'l': 155.83,
              'n': 8940813,
              'o': 190.45,
              't': 1682913600000,
              'v': 604201203.0,
              'vw': 180.0693}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 108,
 'request_id': 'c1ecdfe8cbde85ff7812a150979e68f1',
 'results': [{'c': 166.83,
              'h': 192.38,
              'l': 155.83,
              'n': 8627972,
              'o': 182.42,
              't': 1685592000000,
              'v': 556518356.0,
              'vw': 176.7204}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 87,
 'request_id': 'e4ffa59866cb0937eca0a889634d8ac7',
 'results': [{'c': 166.83,
              'h': 192.38,
              'l': 155.83,
              'n': 7227744,
              'o': 184.3,
              't': 1688184000000,
              'v': 455572834.0,
              'vw': 175.0795}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 67,
 'request_id': '36d468136ce5e0aa427191c49f0d523a',
 'results': [{'c': 166.83,
              'h': 189.97,
              'l': 155.83,
              'n': 5582509,
              'o': 187.49,
              't': 1690862400000,
              'v': 345191065.0,
              'vw': 171.156}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 44,
 'request_id': '2cd7ba7dacf82e0b706542527a192abc',
 'results': [{'c': 166.83,
              'h': 181.82,
              'l': 155.83,
              'n': 4046915,
              'o': 178.73,
              't': 1693540800000,
              'v': 252809232.0,
              'vw': 167.3171}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}

-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 24,
 'request_id': 'b123220bc68eecbf3a70b4a91b1e7bd5',
 'results': [{'c': 166.83,
              'h': 170,
              'l': 155.83,
              'n': 2595908,
              'o': 169.08,
              't': 1696132800000,
              'v': 156982178.0,
              'vw': 162.0982}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Result Date: 2023-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 2,
 'request_id': '31548c961b8dd5940717146943ce1a5c',
 'results': [{'c': 166.83,
              'h': 167.16,
              'l': 162.76,
              'n': 256479,
              'o': 163.67,
              't': 1698811200000,
              'v': 12095883.0,
              'vw': 165.5505}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'PEP'}
-------------------------
Now Finding: BROS
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'message': "Your plan doesn't include this data timeframe. Please upgrade "
            'your plan at https://polygon.io/pricing',
 'request_id': '44fa709d93112127ec555c2fc78f3eac',
 'status': 'NOT_AUTHORIZED'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '488f85fb9f603fdbd0ec8c7fe20d6515',
 'results': [{'c': 36.87,
              'h': 66,
              'l': 20.05,
              'n': 2699940,
              'o': 51.47,
              't': 1641013200000,
              'v': 256441484.0,
              'vw': 44.2476}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '22a95cb3c8c82d0ac834a88b3c608d54',
 'results': [{'c': 36.24,
              'h': 66,
              'l': 20.05,
              'n': 2413430,
              'o': 52.02,
              't': 1643691600000,
              'v': 227739644.0,
              'vw': 43.3747}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'a9e7454a4ed0e3f781f6ddc58b2576a7',
 'results': [{'c': 40.28,
              'h': 66,
              'l': 20.05,
              'n': 2340202,
              'o': 49.11,
              't': 1646110800000,
              'v': 220396837.0,
              'vw': 41.6542}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '885bd0370a2b9218f4b530c05f5b084f',
 'results': [{'c': 34.19,
              'h': 58.6942,
              'l': 20.05,
              'n': 2058481,
              'o': 56.43,
              't': 1648785600000,
              'v': 186041506.0,
              'vw': 37.4877}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'cd594d92fda2740e1d463a6a2d837ad8',
 'results': [{'c': 34.21,
              'h': 54.18,
              'l': 20.05,
              'n': 2014828,
              'o': 47.8,
              't': 1651377600000,
              'v': 180719365.0,
              'vw': 34.5737}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '767885a3360c714b091fd56e5fcca1c1',
 'results': [{'c': 34.11,
              'h': 54.18,
              'l': 27.94,
              'n': 1726725,
              'o': 37.47,
              't': 1654056000000,
              'v': 139577748.0,
              'vw': 36.8808}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '71be3d51103044f2adc02193bf861c3e',
 'results': [{'c': 30.07,
              'h': 54.18,
              'l': 27.94,
              'n': 1794813,
              'o': 31.67,
              't': 1656648000000,
              'v': 137070749.0,
              'vw': 36.4363}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '920cc890c6938eb3b368e61632585584',
 'results': [{'c': 34,
              'h': 54.18,
              'l': 26.93,
              'n': 1954081,
              'o': 37.25,
              't': 1659326400000,
              'v': 147629695.0,
              'vw': 35.6386}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4f078e5ecdcada727f60d4a2fc54da0c',
 'results': [{'c': 34.03,
              'h': 41.4399,
              'l': 26.93,
              'n': 1958424,
              'o': 35.9,
              't': 1662004800000,
              'v': 143300441.0,
              'vw': 33.961}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '2296c507b941016181541e176bc378ac',
 'results': [{'c': 28.66,
              'h': 41.4399,
              'l': 26.93,
              'n': 1973148,
              'o': 31.5,
              't': 1664596800000,
              'v': 145046280.0,
              'vw': 33.5112}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'a70feacfa7391c4be6b8c882aa184384',
 'results': [{'c': 30.28,
              'h': 41.4399,
              'l': 26.93,
              'n': 1902779,
              'o': 37.45,
              't': 1667275200000,
              'v': 136357976.0,
              'vw': 33.3457}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '755d38aaa5038394f37ef8a6a0ae818f',
 'results': [{'c': 27.64,
              'h': 41.4399,
              'l': 25.451,
              'n': 1716758,
              'o': 28.62,
              't': 1672549200000,
              'v': 125211410.0,
              'vw': 31.9529}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '8228db639fe623272e1cde99e4e6cca5',
 'results': [{'c': 28.93,
              'h': 41.4399,
              'l': 25.451,
              'n': 1538338,
              'o': 38.09,
              't': 1675227600000,
              'v': 111463688.0,
              'vw': 31.2882}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '42870242a1c6ed8e420fe9e2d9b6e76e',
 'results': [{'c': 30.68,
              'h': 35.18,
              'l': 25.451,
              'n': 1556183,
              'o': 33.3,
              't': 1677646800000,
              'v': 111888538.0,
              'vw': 30.1497}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'f7c67042c809c1b6e17f2dcae1077d2a',
 'results': [{'c': 23.69,
              'h': 35.09,
              'l': 23.4,
              'n': 1662558,
              'o': 31.64,
              't': 1680321600000,
              'v': 122548680.0,
              'vw': 29.1739}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}

-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '4cecb44b399177896738b8415b08b0a1',
 'results': [{'c': 25.4,
              'h': 35.09,
              'l': 22.665,
              'n': 1722611,
              'o': 31.34,
              't': 1682913600000,
              'v': 127968105.0,
              'vw': 28.1714}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 108,
 'request_id': '05d82f1836002bef4a85d5b26a4acd4b',
 'results': [{'c': 25.96,
              'h': 35.09,
              'l': 22.665,
              'n': 1479728,
              'o': 28.24,
              't': 1685592000000,
              'v': 109655636.0,
              'vw': 27.7163}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 87,
 'request_id': 'e6ebd634be12c142df12c30a618004dd',
 'results': [{'c': 25.96,
              'h': 35.09,
              'l': 22.665,
              'n': 1264501,
              'o': 28.42,
              't': 1688184000000,
              'v': 94672394.0,
              'vw': 27.6069}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 67,
 'request_id': 'a1a2e4edca5b18dae687262a6c3c4d17',
 'results': [{'c': 25.96,
              'h': 35.09,
              'l': 22.665,
              'n': 1076188,
              'o': 30.51,
              't': 1690862400000,
              'v': 81645876.0,
              'vw': 27.3344}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 44,
 'request_id': '6c4f9e8860a92af377e718cb2aa70d1d',
 'results': [{'c': 25.96,
              'h': 29.8299,
              'l': 22.665,
              'n': 709821,
              'o': 29.72,
              't': 1693540800000,
              'v': 54653536.0,
              'vw': 25.358}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 24,
 'request_id': '0acefe42d47020b4482560456dcf7ede',
 'results': [{'c': 25.96,
              'h': 26.43,
              'l': 22.85,
              'n': 325278,
              'o': 23.14,
              't': 1696132800000,
              'v': 23580829.0,
              'vw': 24.7165}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Result Date: 2023-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 2,
 'request_id': '6285140b61a89a9fecabcf4b6e4323c1',
 'results': [{'c': 25.96,
              'h': 26.095,
              'l': 23.31,
              'n': 35394,
              'o': 24.4,
              't': 1698811200000,
              'v': 2761224.0,
              'vw': 24.7157}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'BROS'}
-------------------------
Now Finding: SBUX
-------------------------
-------------------------
Result Date: 2021-11-01
-------------------------
{'message': "Your plan doesn't include this data timeframe. Please upgrade "
            'your plan at https://polygon.io/pricing',
 'request_id': '4563539a7f622b4d86f0871ba5333ad8',
 'status': 'NOT_AUTHORIZED'}
-------------------------
Result Date: 2022-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1bded17b1e5f7ea3fce8a2948722e0de',
 'results': [{'c': 78.11,
              'h': 117.8,
              'l': 68.39,
              'n': 14543812,
              'o': 116.47,
              't': 1641013200000,
              'v': 1268762799.0,
              'vw': 85.3797}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'd438feb445900b0d49b426dd41333f4a',
 'results': [{'c': 81.5,
              'h': 99.15,
              'l': 68.39,
              'n': 13518774,
              'o': 98.4175,
              't': 1643691600000,
              'v': 1173504972.0,
              'vw': 81.7601}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '6ea28bbc368ae17328e2b6ae0a23c654',
 'results': [{'c': 86.92,
              'h': 93.5,
              'l': 68.39,
              'n': 12863680,
              'o': 91.49,
              't': 1646110800000,
              'v': 1121522615.0,
              'vw': 80.3283}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '98a0b5afc6504a57fa85647e2e0a33b0',
 'results': [{'c': 84.7,
              'h': 93.48,
              'l': 68.39,
              'n': 12344026,
              'o': 91.5,
              't': 1648785600000,
              'v': 1073685684.0,
              'vw': 80.1503}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '2013ac3c2cf5517f0dc3735d7af63e7d',
 'results': [{'c': 86.79,
              'h': 93.48,
              'l': 68.39,
              'n': 11621839,
              'o': 75.25,
              't': 1651377600000,
              'v': 1011212382.0,
              'vw': 80.8995}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '14d72b9fb12f0c08129ea5cc5abe3e64',
 'results': [{'c': 97.95,
              'h': 99.53,
              'l': 70.35,
              'n': 10737688,
              'o': 78.75,
              't': 1654056000000,
              'v': 909939770.0,
              'vw': 84.8653}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '2b01c11a9d443513062c76a4fc7271c3',
 'results': [{'c': 98,
              'h': 105.54,
              'l': 75.73,
              'n': 10429808,
              'o': 76.73,
              't': 1656648000000,
              'v': 872180575.0,
              'vw': 89.3456}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '6784fdffe02f547bb0b472e896a32876',
 'results': [{'c': 105.04,
              'h': 107.595,
              'l': 81.67,
              'n': 10561846,
              'o': 84.19,
              't': 1659326400000,
              'v': 869370843.0,
              'vw': 92.3842}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'd4430bae6e59b88c394a61c308ecd1c9',
 'results': [{'c': 103.51,
              'h': 110.83,
              'l': 81.67,
              'n': 10929106,
              'o': 83.7,
              't': 1662004800000,
              'v': 889318807.0,
              'vw': 95.7439}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2022-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '46d77553c2d9095bce24735486581e5c',
 'results': [{'c': 98.34,
              'h': 110.83,
              'l': 82.43,
              'n': 10368190,
              'o': 84.75,
              't': 1664596800000,
              'v': 807709929.0,
              'vw': 98.4406}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}

-------------------------
Result Date: 2022-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '64d74f2e0af428150915236e8cbaca2b',
 'results': [{'c': 109.34,
              'h': 111.11,
              'l': 82.97,
              'n': 10264416,
              'o': 88.06,
              't': 1667275200000,
              'v': 751122676.0,
              'vw': 101.7863}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-01-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '7272a0388eada723ff8c29e6c8c3c754',
 'results': [{'c': 98.23,
              'h': 115.48,
              'l': 96.52,
              'n': 11557334,
              'o': 100.56,
              't': 1672549200000,
              'v': 765299042.0,
              'vw': 103.9128}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-02-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '1c3a85e362f6c9de30470f214e1b4818',
 'results': [{'c': 102.92,
              'h': 115.48,
              'l': 95.55,
              'n': 11956655,
              'o': 108.97,
              't': 1675227600000,
              'v': 767616004.0,
              'vw': 102.9306}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-03-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'f0a9f46acdce82fc93b4f305fd22d234',
 'results': [{'c': 96.46,
              'h': 115.48,
              'l': 95.55,
              'n': 12161541,
              'o': 102.19,
              't': 1677646800000,
              'v': 748323896.0,
              'vw': 102.1521}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-04-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': 'fe3c3fe1c32141c8a52b8b0abb211e0b',
 'results': [{'c': 93.68,
              'h': 115.48,
              'l': 93.03,
              'n': 12293019,
              'o': 104.06,
              't': 1680321600000,
              'v': 748114848.0,
              'vw': 101.3726}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-05-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 120,
 'request_id': '88137f24c9a1e520fbeb91d7820c1c43',
 'results': [{'c': 94.42,
              'h': 115.48,
              'l': 89.21,
              'n': 12317927,
              'o': 114.252,
              't': 1682913600000,
              'v': 757633509.0,
              'vw': 99.2158}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-06-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 108,
 'request_id': 'c217d3b780e46dc97f79df8d3d8d5196',
 'results': [{'c': 100.01,
              'h': 104.46,
              'l': 89.21,
              'n': 11000693,
              'o': 97.59,
              't': 1685592000000,
              'v': 688119986.0,
              'vw': 97.4491}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-07-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 87,
 'request_id': 'c35558a0de90d7de8fe17ba59a9247c7',
 'results': [{'c': 100.01,
              'h': 104.46,
              'l': 89.21,
              'n': 8717838,
              'o': 98.73,
              't': 1688184000000,
              'v': 537193724.0,
              'vw': 96.9278}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-08-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 67,
 'request_id': 'f83b54c434899e8e8017466a4cbee034',
 'results': [{'c': 100.01,
              'h': 104.46,
              'l': 89.21,
              'n': 6640231,
              'o': 101.47,
              't': 1690862400000,
              'v': 405849391.0,
              'vw': 95.7062}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-09-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 44,
 'request_id': '3e297d17c1c63169d7f0c1375594fb18',
 'results': [{'c': 100.01,
              'h': 101.92,
              'l': 89.21,
              'n': 4407215,
              'o': 98.4,
              't': 1693540800000,
              'v': 278809560.0,
              'vw': 94.1343}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-10-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 24,
 'request_id': 'd3928c06cf2c42f9b6eb868438e0e0cd',
 'results': [{'c': 100.01,
              'h': 101.92,
              'l': 89.21,
              'n': 2570335,
              'o': 91.05,
              't': 1696132800000,
              'v': 165678871.0,
              'vw': 93.6594}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Result Date: 2023-11-01
-------------------------
{'adjusted': True,
 'count': 1,
 'queryCount': 2,
 'request_id': '2dda812843fc3ac6debbad508f2fd493',
 'results': [{'c': 100.01,
              'h': 101.92,
              'l': 90.55,
              'n': 436126,
              'o': 91.83,
              't': 1698811200000,
              'v': 37688828.0,
              'vw': 96.779}],
 'resultsCount': 1,
 'status': 'OK',
 'ticker': 'SBUX'}
-------------------------
Done!
-------------------------

In [10]:
#Create dataframe
df = pd.DataFrame(data_list)
df.head()

,status,request_id,message,ticker,queryCount,resultsCount,adjusted,results,count
0,NOT_AUTHORIZED,68f119c09d04ec49fce14fd4ca16f206,Your plan doesn't include this data timeframe....,NaN,NaN,NaN,NaN,NaN,NaN
1,NOT_AUTHORIZED,1f171486e28989049d930ad5f0f1f8cd,Your plan doesn't include this data timeframe....,NaN,NaN,NaN,NaN,NaN,NaN
2,OK,c3fbad86030c8755e1fcd35751491c70,NaN,BUD,120.0,1.0,True,"[{'v': 185073263.0, 'vw': 58.7384, 'o': 62.43,...",1.0
3,OK,a9420ea938d4c9c4836fc3157b7ca229,NaN,BUD,120.0,1.0,True,"[{'v': 176759102.0, 'vw': 57.2436, 'o': 64.01,...",1.0
4,OK,0650ca463b969aade0c1e11e2bd3f9df,NaN,BUD,120.0,1.0,True,"[{'v': 177299717.0, 'vw': 55.898, 'o': 59.94, ...",1.0

In [16]:
#Clean the dataframe
cleandf = df.loc[:, ['ticker', 'results']]
cleandf=cleandf.dropna()
cleandf

    ticker                                            results
2      BUD  [{'v': 185073263.0, 'vw': 58.7384, 'o': 62.43,...
3      BUD  [{'v': 176759102.0, 'vw': 57.2436, 'o': 64.01,...
4      BUD  [{'v': 177299717.0, 'vw': 55.898, 'o': 59.94, ...
5      BUD  [{'v': 160603099.0, 'vw': 54.0878, 'o': 60.79,...
6      BUD  [{'v': 170988591.0, 'vw': 51.7573, 'o': 56.98,...
..     ...                                                ...
134   SBUX  [{'v': 537193724.0, 'vw': 96.9278, 'o': 98.73,...
135   SBUX  [{'v': 405849391.0, 'vw': 95.7062, 'o': 101.47...
136   SBUX  [{'v': 278809560.0, 'vw': 94.1343, 'o': 98.4, ...
137   SBUX  [{'v': 165678871.0, 'vw': 93.6594, 'o': 91.05,...
138   SBUX  [{'v': 37688828.0, 'vw': 96.779, 'o': 91.83, '...

[132 rows x 2 columns]

In [17]:
#Parse the results data
df_new = cleandf.explode('results')
def break_up_dictionary(row):
    results = row['results'][0]
    for key, value in results.items():
        row[key] = value
    return row

df_new = cleandf.apply(break_up_dictionary, axis=1)
stock_df=df_new.loc[:, ['ticker', 'v',"vw","o","c","h","l","t","n"]]
stock_df

,ticker,v,vw,o,c,h,l,t,n
2,BUD,185073263.0,58.7384,62.43,53.94,67.91,50.59,1641013200000,2105726
3,BUD,176759102.0,57.2436,64.01,55.02,66.05,50.59,1643691600000,2060645
4,BUD,177299717.0,55.8980,59.94,52.51,63.45,50.59,1646110800000,2053783
5,BUD,160603099.0,54.0878,60.79,48.57,63.45,47.23,1648785600000,1951050
6,BUD,170988591.0,51.7573,56.98,45.23,58.37,44.51,1651377600000,2004952
...,...,...,...,...,...,...,...,...,...
134,SBUX,537193724.0,96.9278,98.73,100.01,104.46,89.21,1688184000000,8717838
135,SBUX,405849391.0,95.7062,101.47,100.01,104.46,89.21,1690862400000,6640231
136,SBUX,278809560.0,94.1343,98.40,100.01,101.92,89.21,1693540800000,4407215
137,SBUX,165678871.0,93.6594,91.05,100.01,101.92,89.21,1696132800000,2570335
138,SBUX,37688828.0,96.7790,91.83,100.01,101.92,90.55,1698811200000,436126

In [18]:
#Save data to csv
stock_df.to_csv('data.csv', index=True)